# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0005_auto_20160405_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_enroll',
            field=models.IntegerField(null=True),
        ),
    ]
