# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0006_auto_20160405_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
