# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0009_auto_20160411_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='plaza.Course'),
        ),
    ]
