# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0010_auto_20160411_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
