# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0012_auto_20160414_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='receivers',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('ANSWER', 'answered'), ('FOLLOW', 'followed'), ('ASSIGN', 'invited ')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='plaza.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='target_link',
            field=models.URLField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='target_text',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
