# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0013_post_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tag_posts', to='plaza.Tag'),
        ),
    ]
