# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0014_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='field',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='institution',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
