# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0014_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('PDF', 'application/pdf'), ('JPEG', 'image/jpeg'), ('GIF', 'image/gif'), ('MP4', 'video/mp4'), ('EMBED', 'text/html'), ('PNG', 'image/png'), ('CAL', 'text/calendar')], default='0', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='plaza.Person')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='plaza.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='objects',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='post',
        ),
        migrations.DeleteModel(
            name='Objects',
        ),
    ]
