# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0015_auto_20160416_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(blank=True, default='/media/profile-photos/user_ico.png', upload_to='profile-photos'),
        ),
    ]
