# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 22:19
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0016_auto_20160416_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
