# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0016_auto_20160416_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_code',
            field=models.IntegerField(null=True),
        ),
    ]
