# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import plaza.models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0017_auto_20160417_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile-photos/user_ico.png', upload_to=plaza.models.profile_image_rename),
        ),
    ]
