# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0017_auto_20160417_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='root_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entire_thread', to='plaza.Post'),
        ),
    ]
