# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0018_auto_20160417_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'N/A')], max_length=1, null=True),
        ),
    ]
