# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0017_course_access_code'),
        ('plaza', '0018_post_root_id'),
    ]

    operations = [
    ]
