# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0019_merge'),
        ('plaza', '0021_auto_20160417_0829'),
    ]

    operations = [
    ]
