# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0022_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='comments',
        ),
        migrations.AddField(
            model_name='resource',
            name='child',
            field=models.ManyToManyField(related_name='_resource_child_+', to='plaza.Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='due',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='notes',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('D', 'Document'), ('V', 'Video'), ('F', 'Folder'), ('N', 'N/A')], max_length=16),
        ),
    ]
