# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0022_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='types',
            new_name='post_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'resolved'), ('1', 'unresolved'), ('2', 'answered'), ('3', 'unanswered')], default='0', max_length=1),
        ),
    ]
