# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0023_auto_20160419_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='courses',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='plaza.Course'),
            preserve_default=False,
        ),
    ]
