# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0023_auto_20160419_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='plaza.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(default=0, upload_to='resources/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('P', 'Plain'), ('D', 'Document'), ('V', 'Video'), ('F', 'Folder'), ('N', 'N/A')], max_length=16),
        ),
    ]
