# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0025_auto_20160419_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='plaza.Course'),
        ),
    ]
