# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0025_remove_resource_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='child',
            field=models.ManyToManyField(null=True, related_name='resource_parent', to='plaza.Resource'),
        ),
    ]
