# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0026_auto_20160419_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='child',
        ),
        migrations.AddField(
            model_name='resource',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='plaza.Resource'),
        ),
    ]
