# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0027_auto_20160419_1824'),
        ('plaza', '0028_auto_20160419_2107'),
    ]

    operations = [
    ]
