# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0029_merge'),
        ('plaza', '0029_remove_post_visibility'),
    ]

    operations = [
    ]
