# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0030_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='course',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_text',
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_content',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('0', ' answered your question'), ('1', ' followed your question'), ('2', ' assigned you a question'), ('3', ' upvoted your answer'), ('4', ' commented your answer'), ('5', ' replied to your comments'), ('6', ' posted a new question in your following tag'), ('7', ' followed you')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='destination',
            field=models.URLField(max_length=256),
        ),
    ]
