# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plaza', '0030_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='assignees',
        ),
        migrations.AddField(
            model_name='post',
            name='assignee',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
