# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0033_auto_20160420_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='courses',
            new_name='course',
        ),
    ]
