# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0035_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='plaza.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('0', ' answered your question'), ('1', ' followed your question'), ('2', ' commented your question'), ('3', ' upvoted your answer'), ('4', ' downvoted your answer'), ('5', ' replied to your comments'), ('6', ' posted a new question in your following tag'), ('7', ' followed you'), ('8', ' add you to a team')], max_length=1),
        ),
    ]
